"""Generates llm_real/run_colab.ipynb. Run locally (`python build_notebook.py`) whenever the
notebook's cell content needs to change -- editing the .ipynb JSON by hand is error-prone, so
this script is the source of truth. Mirrors llm/build_notebook.py's structure (GPU check,
config, Drive mount, clone, install, preflight, determinism, resume) but targets its OWN Drive
results folder (`grpo_llm_real_results`, distinct from llm/'s `grpo_llm_results`) and STOPS
after the Step 2 pilot gate -- this is a gated pilot, not a full sweep."""
import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

GITHUB_USER = "nilay47"
GITHUB_REPO = "agenthon"


def md(*lines):
    return new_markdown_cell("\n".join(lines))


def code(*lines):
    return new_code_cell("\n".join(lines))


cells = [
    md(
        "# Day-1 realistic LLM experiment: Colab A100 runner (GATED)",
        "",
        "One-click pipeline for a REALISTIC version of the `llm/` conflicting-preference",
        "experiment: Qwen2.5-0.5B-Instruct + LoRA, TRL `GRPOTrainer`, on real **GSM8K** math",
        "word problems instead of a synthetic integer-picking task. Every training prompt is",
        "randomly assigned (50/50, hidden from the model) to one of two REAL graders that",
        "disagree about HOW to answer correctly, not WHETHER:",
        "",
        "- **Grader A, \"reasoning rubric\" (0-10)**: `10 * correct * min(1, n_tokens/320)` --",
        "  rewards a correct final answer that GROWS with completion length, saturating only",
        "  at the full completion budget (not a trivial line-count cap -- see v4's note below).",
        "- **Grader B, \"terse verifier\" (0-1, SMOOTH)**: `correct * max(0, 1 - n_tokens/400)` --",
        "  rewards a correct final answer that tapers LINEARLY to 0 by 400 tokens, not a hard",
        "  cliff (v1's hard `<=40 tokens` cliff meant essentially no real-model completion ever",
        "  qualified, leaving grader B with zero reward AND zero signal everywhere).",
        "",
        "Final-answer parsing falls back through three tiers: `#### <number>`, then",
        "`\\boxed{<number>}`, then the LAST number anywhere in the completion (v1's strict",
        "`#### only` parse left most completions unparsable, starving both graders).",
        "Correctness is shared; verbosity conflicts. The two graders' NATIVE scales (0-10 vs",
        "0-1) are themselves a realistic version of `llm/`'s artificial per-family reward-scale",
        "`k` -- there is no synthetic scaling knob here.",
        "",
        "**v2**: a HARD baseline gate -- Step 1 must show accuracy >= 20% AND both graders'",
        "true within-GROUP reward std > 0 before Step 2 is allowed to spend any GPU time.",
        "",
        "**v3 (attempt 4)**: v2's 200-token completion cap turned out to BE the problem --",
        "completions were getting truncated at the cap (median length = 200), which hurt",
        "accuracy and left grader B's reward near 0 (`1 - 200/200 ~ 0`). Raised the cap to 320",
        "and grader B's taper denominator to 400. Step 1 also now tries",
        "`config.MODEL_NAME` (Qwen2.5-0.5B-Instruct) first and AUTOMATICALLY retries with",
        "`config.MODEL_NAME_FALLBACK` (Qwen2.5-1.5B-Instruct) if the small model can't clear",
        "the accuracy gate. Every attempt (pass or fail, baseline or pilot) is appended to",
        "`attempts.json` on Drive -- the one file that survives every results archive below, so",
        "the full history of what was tried stays honest.",
        "",
        "**v4 (attempt 5)**: attempt 4's pilot FAILED (length ratio 0.972, needed <=0.85) for two",
        "compounding reasons -- grader A's old line-count cap (6 lines) saturated almost",
        "immediately (the model naturally writes well over 6 lines), so it gave NO gradient",
        "pushing length further -- no real tension with grader B's terseness pull; and LR=1e-5",
        "was too small for LoRA to move length more than 10-18 tokens over 80 steps regardless.",
        "Grader A is now TOKEN-based (saturates at `MAX_COMPLETION_LENGTH`, like grader B), and",
        "LR is raised to 5e-5. The pilot gate is restated as PASS iff Dr.GRPO's length >= 1.15x",
        "GRPO's (pre-registered for this attempt). Since the 0.5B model already passed Step 1 in",
        "attempt 4, Step 1 here skips the fallback-model retry and just re-confirms the new",
        "reward design's group reward std. Old results are now ARCHIVED (not deleted) into a",
        "dated subfolder before each redesign, so attempt 4's actual numbers stay on Drive.",
        "",
        "**This notebook is GATED: it STOPS after the Step 2 pilot gate.** No full sweep yet.",
        "All results are saved to Google Drive under `grpo_llm_real_results/` -- a SEPARATE",
        "folder from `llm/`'s `grpo_llm_results/`, so this never touches `llm/`'s results.",
    ),
    md(
        "## 1. Check for a GPU",
        "",
        "Sets `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` before torch ever loads.",
    ),
    code(
        "import os",
        "",
        'os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"',
        "",
        "import subprocess",
        "",
        "try:",
        "    import torch",
        "    has_gpu = torch.cuda.is_available()",
        "except ImportError:",
        "    has_gpu = False",
        "",
        "if not has_gpu:",
        "    raise RuntimeError(",
        "        'No GPU detected. Go to Runtime > Change runtime type, select a GPU '",
        "        '(A100 recommended), then Runtime > Restart session and run all cells again.'",
        "    )",
        "",
        "print(subprocess.run(['nvidia-smi'], capture_output=True, text=True).stdout)",
    ),
    md("## 2. Config -- edit if your fork/repo name differs"),
    code(
        f'GITHUB_USER = "{GITHUB_USER}"',
        f'GITHUB_REPO = "{GITHUB_REPO}"',
        '# Deliberately a DIFFERENT folder from llm/\'s "grpo_llm_results" -- this experiment',
        "# must never read or write llm/'s results.",
        'DRIVE_RESULTS_DIR = "/content/drive/MyDrive/grpo_llm_real_results"',
        'REPO_DIR = f"/content/{GITHUB_REPO}"',
    ),
    md(
        "## 3. Mount Google Drive",
        "",
        "Shares the SAME HuggingFace cache location as `llm/`'s notebook (just a model/dataset",
        "download cache, not results) so the Qwen2.5-0.5B weights don't need a second download.",
    ),
    code(
        "from google.colab import drive",
        "import os",
        "",
        "drive.mount('/content/drive')",
        "os.makedirs(DRIVE_RESULTS_DIR, exist_ok=True)",
        'print(f"Results will be saved to {DRIVE_RESULTS_DIR}")',
        "",
        'os.environ["HF_HOME"] = "/content/drive/MyDrive/hf_cache"',
        'os.makedirs(os.environ["HF_HOME"], exist_ok=True)',
        "hf_home = os.environ['HF_HOME']",
        'print(f"HF cache: {hf_home}")',
    ),
    md(
        "## 3b. Archive old results (keep attempts.json)",
        "",
        "Each redesign (reward function, parsing logic, prompt template, training size, model)",
        "makes every number in an OLDER result file stale for comparison against FRESH runs --",
        "but attempt 4's actual numbers are worth keeping, not discarding. MOVES everything",
        "currently at the top level of `DRIVE_RESULTS_DIR` (preflight files, baseline check, run",
        "results, pilot summary) into `archive/<ARCHIVE_LABEL>/`, leaving the top level clean",
        "for this attempt's fresh runs. `attempts.json` and the `archive/` folder itself are",
        "never moved -- `attempts.json` is the one file meant to survive every redesign.",
        "",
        "**Bump `ARCHIVE_LABEL` below each time you redesign, BEFORE rerunning this cell** --",
        "it's just a folder name, not auto-derived from `attempts.json`.",
    ),
    code(
        "import shutil",
        "",
        "ARCHIVE_LABEL = 'attempt_4'  # the PREVIOUS attempt's results being archived by this run",
        "",
        "archive_dir = os.path.join(DRIVE_RESULTS_DIR, 'archive', ARCHIVE_LABEL)",
        "if os.path.exists(DRIVE_RESULTS_DIR):",
        "    _moved = False",
        "    for _name in os.listdir(DRIVE_RESULTS_DIR):",
        "        if _name in ('attempts.json', 'archive'):",
        "            continue",
        "        os.makedirs(archive_dir, exist_ok=True)",
        "        _src = os.path.join(DRIVE_RESULTS_DIR, _name)",
        "        _dst = os.path.join(archive_dir, _name)",
        "        print(f'archiving {_src} -> {_dst}')",
        "        shutil.move(_src, _dst)",
        "        _moved = True",
        "    if not _moved:",
        "        print('nothing to archive (top level was already clean)')",
        "os.makedirs(DRIVE_RESULTS_DIR, exist_ok=True)",
        'print(f"{DRIVE_RESULTS_DIR} top level is clean (old results under archive/{ARCHIVE_LABEL}/, attempts.json preserved)")',
    ),
    md(
        "## 4. Clone the repo",
        "",
        "If the repo is **private**, add a `GITHUB_TOKEN` Colab secret first (key icon in the",
        "left sidebar) with a personal access token that has `repo` scope.",
    ),
    code(
        "import os",
        "",
        "token = None",
        "try:",
        "    from google.colab import userdata",
        "    token = userdata.get('GITHUB_TOKEN')",
        "except Exception:",
        "    pass",
        "",
        "if token:",
        '    clone_url = f"https://{token}@github.com/{GITHUB_USER}/{GITHUB_REPO}.git"',
        "else:",
        '    clone_url = f"https://github.com/{GITHUB_USER}/{GITHUB_REPO}.git"',
        "",
        "if not os.path.exists(REPO_DIR):",
        "    !git clone {clone_url} {REPO_DIR}",
        "else:",
        '    print(f"{REPO_DIR} already exists, skipping clone (pulling latest instead)")',
        "    !cd {REPO_DIR} && git pull",
        "",
        "%cd {REPO_DIR}/llm_real",
    ),
    md(
        "## 5. Install dependencies (Colab-safe: never touches torch/CUDA)",
        "",
        "Reuses `llm/requirements-colab.txt` as-is (same five packages -- `trl`/`peft`/",
        "`transformers`/`accelerate`/`datasets` -- installed with `--no-deps`, so pip never",
        "resolves their own torch dependency against Colab's preinstalled build). `datasets`",
        "is what loads GSM8K here too, no extra dependency needed.",
    ),
    code(
        "!pip install -q --no-deps -r ../llm/requirements-colab.txt",
        "!pip install -q huggingface_hub tokenizers safetensors regex pyyaml filelock requests \\",
        "    tqdm packaging psutil pandas pyarrow dill multiprocess fsspec xxhash scipy",
        "!pip uninstall -y -q torchao",
        "",
        "import importlib.metadata as _metadata",
        "",
        "for _pkg in ['torch', 'transformers', 'trl', 'peft', 'accelerate', 'datasets']:",
        "    try:",
        "        _ver = _metadata.version(_pkg)",
        "    except _metadata.PackageNotFoundError:",
        "        _ver = 'NOT INSTALLED'",
        '    print(f"{_pkg} == {_ver}")',
        "",
        "import torch",
        "",
        'print(f"torch.__version__ = {torch.__version__}")',
        'print(f"torch.version.cuda = {torch.version.cuda}")',
        'print(f"torch.cuda.is_available() = {torch.cuda.is_available()}")',
        "",
        "try:",
        "    import trl.trainer.grpo_trainer  # noqa: F401",
        "    from peft import LoraConfig, get_peft_model  # noqa: F401",
        '    print("trl.trainer.grpo_trainer and peft imported OK")',
        "except Exception as e:",
        "    raise RuntimeError(",
        '        f"Import check failed against torch {torch.__version__} (CUDA {torch.version.cuda}). "',
        '        f"Original error: {e!r}"',
        "    ) from e",
    ),
    md(
        "## 5b. PREFLIGHT: exercise GRPO and Dr.GRPO on 2 tiny steps",
        "",
        "Loads the real model + LoRA and runs 2 GRPO steps (2 prompts x G=4, 16-token",
        "completions) for each of the two methods the pilot gate compares, including one eval",
        "callback call and one save to the Drive `preflight/` subfolder each -- the exact same",
        "code path `run.py` uses for the real runs, just small enough to finish in seconds. Also",
        "exercises the real GSM8K load + grader-assignment path.",
    ),
    code(
        "import os",
        "import sys",
        "sys.path.insert(0, '.')",
        "import config",
        "from run import run_one",
        "",
        "PREFLIGHT_DIR = os.path.join(DRIVE_RESULTS_DIR, 'preflight')",
        "",
        "for _method in config.METHODS:",
        "    print(f'--- preflight: {_method} ---')",
        "    try:",
        "        run_one(_method, seed=0, max_steps=2, out_dir=PREFLIGHT_DIR,",
        "                prompts_per_step=2, g=4, max_completion_length=16, eval_every=1, n_eval_periodic=3)",
        "    except Exception as e:",
        "        raise RuntimeError(",
        '            f"PREFLIGHT FAILED for config \'{_method}\'. Original error: {e!r}"',
        "        ) from e",
        "",
        'print("PREFLIGHT PASSED")',
    ),
    md(
        "## 5c. PREFLIGHT: peak GPU memory at the REAL batch shape",
        "",
        "The config-smoke preflight above uses a tiny 2-prompt batch and 16-token completions,",
        "which doesn't stress memory. This runs ONE micro-batch step at the ACTUAL training",
        "shape (`config.PROMPTS_PER_STEP` x `config.G` = 64 completions per optimizer step,",
        "`config.MAX_COMPLETION_LENGTH`=320 tokens, with completions forced out to the full",
        "length via `min_new_tokens` -- the true worst case) and reports peak GPU memory. Unlike",
        "`llm/`'s 8-token task, this task keeps gradient checkpointing ON and a conservative",
        "`config.MICRO_BATCH_COMPLETIONS` by default specifically because 320-token completions",
        "are ~40x bigger. Fails if peak reserved memory exceeds 34 GB (A100 is 40GB) -- reduce",
        "`config.MICRO_BATCH_COMPLETIONS` and rerun if it does. (Uses `config.MODEL_NAME`, i.e.",
        "the PRIMARY model -- Step 1 below separately checks the fallback model's eval-time",
        "memory if it's ever used.)",
    ),
    code(
        "import torch",
        "",
        "torch.cuda.reset_peak_memory_stats()",
        "run_one('grpo', seed=0, max_steps=1, out_dir=PREFLIGHT_DIR,",
        "        prompts_per_step=config.PROMPTS_PER_STEP, g=config.G,",
        "        max_completion_length=config.MAX_COMPLETION_LENGTH, eval_every=1, n_eval_periodic=3,",
        "        extra_grpo_kwargs=dict(generation_kwargs=dict(min_new_tokens=config.MAX_COMPLETION_LENGTH)))",
        "",
        "peak_allocated_gb = torch.cuda.max_memory_allocated() / 1024**3",
        "peak_reserved_gb = torch.cuda.max_memory_reserved() / 1024**3",
        'print(f"peak memory allocated: {peak_allocated_gb:.2f} GB")',
        'print(f"peak memory reserved:  {peak_reserved_gb:.2f} GB")',
        "",
        "if peak_reserved_gb > 34:",
        "    current_micro = config.MICRO_BATCH_COMPLETIONS",
        "    raise RuntimeError(",
        '        f"Peak GPU memory ({peak_reserved_gb:.2f} GB reserved) exceeds the 34 GB safety "',
        '        f"threshold for a 40GB A100. Reduce config.MICRO_BATCH_COMPLETIONS (currently "',
        '        f"{current_micro}) and rerun this cell."',
        "    )",
        'print("MEMORY PREFLIGHT PASSED")',
    ),
    md(
        "## 6. STEP 1: baseline sanity check (no training) -- HARD GATE",
        "",
        "Runs the UNTRAINED model (`config.MODEL_NAME`, Qwen2.5-0.5B-Instruct) on all 200",
        "reserved held-out GSM8K test problems: accuracy, completion-length and n_steps",
        "distributions, each grader's unscaled reward mean and across-problem population std,",
        "plus the TRUE within-GROUP reward std (G samples of the SAME prompt, matching GRPO's",
        "own group -- the quantity GRPO's advantage computation actually depends on, not the",
        "population std).",
        "",
        "**`--skip_fallback` is passed this attempt**: the 0.5B model already passed Step 1 in",
        "attempt 4, so this run just re-confirms accuracy AND both graders' group reward std",
        "under the NEW (token-based) grader A -- no need to spend time trying the 1.5B fallback",
        "again. (Omit the flag in a future attempt if the model itself is ever in question.)",
        "",
        "**Gate: accuracy >= 20% (`config.BASELINE_MIN_ACCURACY`) AND both graders' group",
        "reward std > 0.** Step 2 below reads this and REFUSES to run (no GPU time spent) if",
        "it's False. This cell ALSO sets `config.MODEL_NAME` in this notebook's own kernel to",
        "match whichever model `baseline_eval.json` reports -- `baseline_eval.py` runs as a",
        "separate subprocess, so its own internal model switch does not otherwise propagate",
        "back here, and every later cell (determinism check, pilot gate) builds its model from",
        "this kernel's `config.MODEL_NAME`.",
    ),
    code(
        '!python baseline_eval.py --out_dir "{DRIVE_RESULTS_DIR}" --skip_fallback',
        "",
        "import json, os",
        'with open(os.path.join(DRIVE_RESULTS_DIR, "baseline_eval.json")) as f:',
        "    baseline_result = json.load(f)",
        "print(baseline_result)",
        "",
        "config.MODEL_NAME = baseline_result['model_name']",
        'print(f"\\nconfig.MODEL_NAME set to {config.MODEL_NAME} for all later cells")',
    ),
    md(
        "## 7. Determinism check",
        "",
        "Two SEPARATE `run_one()` calls with the SAME method+seed (1 step each) should produce",
        "(nearly) identical first-step advantages -- confirming seeding (LoRA init, GSM8K",
        "grader assignment, generation sampling) is reproducible end to end in this new task,",
        "before trusting the single-seed pilot gate below.",
    ),
    code(
        "import sys",
        "sys.path.insert(0, '.')",
        "from check_determinism import run_check",
        "",
        "determinism_passed, determinism_rel_diff = run_check(method='grpo', seed=0)",
    ),
    md(
        "## 8. STEP 2: PILOT GATE (1 seed) -- STOPS HERE",
        "",
        "**Refuses to run at all if Step 1's `gate_passed` was False** (prints why and stops --",
        "no GPU time spent). Otherwise runs Dr.GRPO and GRPO (1 seed each, using whichever",
        "model Step 1 selected) on the real GSM8K conflicting-grader mix.",
        "",
        "**PRE-REGISTERED gate (attempt 5), kept exactly as specified: PASS iff Dr.GRPO's final",
        "mean completion length >= `config.PILOT_GATE_MIN_DRGRPO_TO_GRPO_LENGTH_RATIO` (1.15) x",
        "GRPO's.** Dr.GRPO lacks GRPO's per-group reward normalization and is predicted to be",
        "pulled toward the verbose (0-10) grader, so it should end up noticeably longer. Prints",
        "PASS/FAIL with completion length, accuracy, AND both graders' mean reward for BOTH",
        "runs, the full length TRAJECTORY (mean_n_tokens at every 20-step eval point) for both",
        "runs, plus wall-clock per run; on FAIL, also prints diagnostics (did length move from",
        "baseline at all? did accuracy move at all?) using Step 1's numbers. Every call",
        "(refused or completed) is appended to `attempts.json`.",
        "",
        "**The TRAINING comparison stops here.** Section 9 below is a SEPARATE, NO-TRAINING",
        "measurement job -- it does not depend on whether this gate passed or failed, and uses",
        "its own fresh LoRA init rather than anything this pilot trained.",
    ),
    code(
        "from pilot_gate import run_pilot_gate",
        "",
        "pilot_summary = run_pilot_gate(seed=0, out_dir=DRIVE_RESULTS_DIR, skip_existing=True)",
    ),
    md(
        "## 9. Gradient-field measurement (NO TRAINING)",
        "",
        "A separate diagnostic, independent of the pilot gate above: at a FRESHLY INITIALIZED",
        "LoRA checkpoint (same LoRA config and seed as training, `config.MODEL_NAME` -- whichever",
        "model Step 1 selected), characterizes the gradient GEOMETRY of the two conflicting",
        "graders directly, using TRL's own `_compute_loss` (loss_type=\"dr_grpo\") rather than a",
        "reimplementation -- `gradient_field.validate_loss_equivalence()` asserts this to 1e-5",
        "relative against a real training step's own gradient before anything else runs, and",
        "the cell below raises immediately if that check fails.",
        "",
        "**Paired design**: 128 GSM8K prompts x G=8 completions, generated ONCE, scored by BOTH",
        "graders. Per prompt: `g_i^X` (Dr.GRPO advantages, grader X) and `h_i^X` (GRPO",
        "advantages) for X in {A,B}. Aggregates `U_A^dr, U_B^dr, U^dr` and `U_A^grpo, U_B^grpo,",
        "U^grpo` (a 50/50 grader mixture) are reported with **bootstrap-over-PROMPTS 95% CIs**",
        "(2000 resamples, via a Gram-matrix reduction -- see `build_gram_matrices`/",
        "`bootstrap_stats`'s docstrings for why the ~35MB-per-vector raw gradients never need to",
        "be held in memory through all 2000 resamples): the angle between `U^grpo` and `U^dr`,",
        "`cos(U_A^dr, U_B^dr)` (do the graders conflict in gradient space at all), the norm",
        "ratio `||U_B||/||U_A||` under each method and `R` = their ratio, and the median",
        "per-prompt reward-std ratio `s_A/s_B` for comparison.",
        "",
        "**Finite-G curve**: on 16 of the 128 prompts, draws G=64 completions, computes the",
        "GRPO-style update `U_64`, then for G in {2,4,8,16,32} draws 200 random NESTED subsets",
        "(true subsets of the same 64, not independent resamples) and reports the pooled",
        "median/5-95% range of `cos(U_G, U_64)` -- a small G-vs-cosine figure is saved.",
        "",
        "**Pre-registered BEFORE running** (written to `attempts.json`, stage",
        "`gradient_field_prereg`): substantive iff `angle(U^grpo, U^dr) >= 20` degrees AND the",
        "POINT ESTIMATE of `cos(U_A^dr, U_B^dr) <= 0.1`. All CIs are reported regardless of",
        "outcome (labelled \"bootstrap over prompts\").",
        "",
        "**Runtime**: no GPU was available to benchmark this directly, so treat this as a rough",
        "order-of-magnitude estimate, not a guarantee -- the cell prints its own LIVE,",
        "measured-and-extrapolated ETA for both the paired design and the finite-G curve as it",
        "runs, which is the authoritative number. Target: under 2.5h on an A100.",
    ),
    code(
        "import argparse",
        "from gradient_field import main as run_gradient_field",
        "",
        "gradient_field_results = run_gradient_field(",
        "    argparse.Namespace(out_dir=DRIVE_RESULTS_DIR, seed=0))",
    ),
]

notebook = new_notebook(cells=cells, metadata={
    "accelerator": "GPU",
    "colab": {"gpuType": "A100", "provenance": []},
    "kernelspec": {"display_name": "Python 3", "name": "python3"},
    "language_info": {"name": "python"},
})

nbformat.validate(notebook)
with open("run_colab.ipynb", "w") as f:
    nbformat.write(notebook, f)
